### ISSUE TITLE
No needs double `data`

### ISSUE THREAD

**Issue by jeremysu0131** [zmts/beauty-vuejs-boilerplate#3]
https://github.com/zmts/beauty-vuejs-boilerplate/blob/893d28205f0056ab1ab51ef5a8e1db580f20913a/src/services/base.service.js#L57

When I use the template, it will show `data` is undefined. But I can get the API result when I change response.data.data to response.data. Are there any problem with my setting? The axios version I use is `"^0.18.0"`. Thank you.

**Comment by zmts** [comment]
It's OK to change `response.data.data` to `response.data`. You can change all what you need up to your API.

**Comment by jeremysu0131** [comment]
Thank you. Now I know that I can change everything I want!
