### ISSUE TITLE
problem with requiring images dynamically

### ISSUE THREAD

**Issue by samg0rd** [zmts/beauty-vuejs-boilerplate#4]
i'm having this problem that when i require an img based on what i get back from the data base, if the required image is not in my assets it prevents my component to render/re-render and gives me a webpack error . 
i want to be able to have a conditional rule for it, like if the required image wasn't there, the component renders normally and the image place become empty or shows a default icon. 
is there any solution for that?

my requiring syntax is like this : 
`
<img :src="require(`@/assets/icons/${currency.symbol}.png`) />
`
if the ${ingredients.symbol}.png was found in my assets icons folder it shows it . but if it's not it breaks the component!

**Comment by zmts** [comment]
This issue not in any way related to boilerplate.
