### ISSUE TITLE
npm run build uglifyjs error

### ISSUE THREAD

**Issue by samg0rd** [zmts/beauty-vuejs-boilerplate#5]
Hi, i'm trying to build my Vue project with "npm run build" command. but i keep getting some error related to UglifyJs -->

ERROR in static/js/vendor.46ca10154a1b16022343.js from UglifyJs
Unexpected token name «i», expected punc «;» [./node_modules/base-x/index.js:15,0][static/js/vendor.46ca10154a1b16022343.js:42282,11]

any idea about what is going on?
any help would be greatly appreciated.

**Comment by zmts** [comment]
@simonestic this issue was happened with `beauty-vuejs-boilerplate` ?

**Comment by samg0rd** [comment]
yes.  we build our project up on beauty-vuejs-boilerplate and now we want to deploy it, so we have to build it first with npm run build command and we get this error . also our code contains es6 javascript and that might be the problem here . when we comment UglifyJs out from the webpack building process it builds the project fine but that is not the option for us.

**Comment by zmts** [comment]
Boilerplate updated to vue cli3 and last dependencies.
Try to update project and run build again.

**Comment by samg0rd** [comment]
thanks very much , i actually solved my problem with the help of this article : 

https://blog.dripstat.com/using-es6-with-webpack-3-in-production/

good to know that the boilerplate updated to vue cli3.
thanks again

**Comment by zmts** [comment]
Great! :)
