### ISSUE TITLE
Is there backend example source?

### ISSUE THREAD

**Issue by devjiro76** [zmts/beauty-vuejs-boilerplate#8]
Thanks for this amazing boilerplate :) really.

i cloned this repo and am looking around.
by the way i found there is no way i can login.
as far as i found it looks like i have to prepare backend server to login, right?

of course i can ignore auth logic but i want to look around backend sever example source either.
can you give me how can i found proper source for backend?

Sorry about my stoopid English ;(

**Comment by zmts** [comment]
Hi! I believe you faced with fingerprint requirement issue :) I added this feature in last commits.
Any way you can use https://github.com/zmts/supra-api-nodejs to play with it.
